process.env.DATABASE_URL = "postgresql://tinymart:tinymart@localhost:5432/tinymart_test"
process.env.STRIPE_SECRET_KEY = "sk_test_fake_key_for_testing"
process.env.STRIPE_WEBHOOK_SECRET = "whsec_fake_secret_for_testing"
process.env.PORT = "0"
process.env.NODE_ENV = "test"
